//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Design
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DesignModelContainer : DbContext
    {
        public DesignModelContainer()
            : base("name=DesignModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<CommentRating> CommentRatings { get; set; }
        public virtual DbSet<GeoActual> GeoActuals { get; set; }
        public virtual DbSet<Geo> Geos { get; set; }
        public virtual DbSet<GeoTag> GeoTags { get; set; }
        public virtual DbSet<GeoRating> GeoRatings { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
    }
}
