//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Design
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoRating
    {
        public int Id { get; set; }
        public int GeoId { get; set; }
        public int OwnerId { get; set; }
        public System.DateTime Date { get; set; }
        public int Value { get; set; }
    
        public virtual Geo Geo { get; set; }
    }
}
