//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDataLayer.EntityModel.Design
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Teacher = new HashSet<Teacher>();
        }
    
        public int Id { get; set; }
        public int IdPerson { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Teacher> Teacher { get; set; }
    }
}
