//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDataLayer.EntityModel.Design
{
    using System;
    using System.Collections.Generic;
    
    public partial class Learner
    {
        public Learner()
        {
            this.Parent = new HashSet<Parent>();
        }
    
        public int IdPerson { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string School { get; set; }
        public string Class { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<Parent> Parent { get; set; }
    }
}
