//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDataLayer.EntityModel.Design
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public Parent()
        {
            this.Learner = new HashSet<Learner>();
        }
    
        public int IdPerson { get; set; }
        public string JobPlace { get; set; }
        public string Office { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<Learner> Learner { get; set; }
    }
}
